spring:
  jpa:
    show-sql: true       # вывод SQL-запросов
output:
  ansi:
  enabled: always    # цветной вывод логотипа
logging:
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss"  # кастомный формат даты в логах

app:
  welcome-message: "Welcome to Spring blog!"  # наше кастомное сообщение

my-option:
  admin-email: "booom@ya.ru"
  admins:
      - "gjoinsey1@blogger.com"
      - "scrosi4@cam.ac.uk"
      - "brundle@cam.ac.uk"

yaml spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true
        jpa:
          hibernate:
            ddl-auto: update
            show-sql: true